import { realpathSync } from 'node:fs';
import { basename, dirname, resolve } from 'node:path';

/** A value generated by Dark Kitchen, independent of an external provider. */
export type StableId<Name extends string> = string & {
  readonly __darkKitchenStableId: Name;
};

export type ProjectId = StableId<'project'>;
export type TaskId = StableId<'task'>;
export type TaskDependencyId = StableId<'task-dependency'>;
export type TaskGraphId = StableId<'task-graph'>;
export type RunId = StableId<'run'>;
export type WorkflowRunId = StableId<'workflow-run'>;
export type AgentSessionId = StableId<'agent-session'>;
export type WorkspaceId = StableId<'workspace'>;
export type InterventionId = StableId<'intervention'>;
export type ExecutionNodeId = StableId<'execution-node'>;
export type RepositoryId = StableId<'repository'>;
export type PullRequestId = StableId<'pull-request'>;
export type CheckId = StableId<'check'>;
export type ConfigurationId = StableId<'configuration'>;
export type EventId = StableId<'event'>;
export type ChannelMessageId = StableId<'channel-message'>;

/** An identifier owned by an adapter. It is never used as a domain identity. */
export interface ProviderReference {
  readonly provider: string;
  readonly id: string;
  readonly url?: string;
}

export type TrackerReference = ProviderReference;
export type ScmReference = ProviderReference;

export type TaskStatus = 'backlog' | 'ready' | 'active' | 'blocked' | 'completed' | 'cancelled';

export interface Project {
  readonly id: ProjectId;
  readonly name: string;
  readonly trackerReference?: TrackerReference;
  readonly repositoryId?: RepositoryId;
  readonly createdAt: string;
  readonly updatedAt: string;
}

export interface Task {
  readonly id: TaskId;
  readonly projectId: ProjectId;
  readonly title: string;
  readonly description?: string;
  /** Provider-normalized labels/tags used by scheduling and workflow selection. */
  readonly labels?: readonly string[];
  readonly status: TaskStatus;
  readonly trackerReference?: TrackerReference;
  readonly createdAt: string;
  readonly updatedAt: string;
}

export type TaskDependencyKind = 'blocks' | 'related';

export interface TaskDependency {
  readonly id: TaskDependencyId;
  readonly taskId: TaskId;
  readonly dependsOnTaskId: TaskId;
  readonly kind: TaskDependencyKind;
}

export interface TaskGraph {
  readonly id: TaskGraphId;
  readonly projectId: ProjectId;
  readonly taskIds: readonly TaskId[];
  readonly dependencies: readonly TaskDependency[];
  readonly createdAt: string;
  readonly updatedAt: string;
}

export type RuntimeState =
  | 'queued'
  | 'starting'
  | 'running'
  | 'waiting'
  | 'blocked'
  | 'completed'
  | 'failed'
  | 'stopped'
  | 'interrupted';

export type TerminalRuntimeState = Extract<RuntimeState, 'completed' | 'failed' | 'stopped'>;

export type RunState = RuntimeState;

export interface ExecutionNode {
  readonly id: ExecutionNodeId;
  readonly runId: RunId;
  readonly taskId: TaskId;
  readonly state: RuntimeState;
  readonly agentSessionId?: AgentSessionId;
  readonly createdAt: string;
  readonly updatedAt: string;
}

export interface Run {
  readonly id: RunId;
  readonly projectId: ProjectId;
  readonly taskId: TaskId;
  readonly workflowRunId?: WorkflowRunId;
  readonly state: RunState;
  readonly executionNodeIds: readonly ExecutionNodeId[];
  readonly workspaceId?: WorkspaceId;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly completedAt?: string;
}

export interface WorkflowRun {
  readonly id: WorkflowRunId;
  readonly projectId: ProjectId;
  readonly taskGraphId: TaskGraphId;
  readonly state: RunState;
  readonly runIds: readonly RunId[];
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly completedAt?: string;
}

export type AgentSessionState =
  | 'starting'
  | 'running'
  | 'waiting'
  | 'blocked'
  | 'completed'
  | 'failed'
  | 'stopped'
  | 'interrupted';

export interface AgentSession {
  readonly id: AgentSessionId;
  readonly runId: RunId;
  readonly taskId: TaskId;
  readonly executionNodeId: ExecutionNodeId;
  readonly workspaceId: WorkspaceId;
  readonly state: AgentSessionState;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly completedAt?: string;
}

export type WorkspaceKind = 'primary-worktree' | 'auxiliary';
export type WorkspaceState = 'provisioning' | 'active' | 'released' | 'failed';

export interface Workspace {
  readonly id: WorkspaceId;
  readonly projectId: ProjectId;
  readonly taskId: TaskId;
  readonly repositoryId: RepositoryId;
  readonly kind: WorkspaceKind;
  readonly state: WorkspaceState;
  readonly path: string;
  readonly revision?: string;
  readonly createdAt: string;
  readonly updatedAt: string;
}

export interface PrimaryWorktreeAssignment {
  readonly taskId: TaskId;
  readonly workspaceId: WorkspaceId;
}

export type InterventionTarget =
  | { readonly scope: 'task'; readonly targetId: TaskId }
  | { readonly scope: 'run'; readonly targetId: RunId }
  | { readonly scope: 'agent'; readonly targetId: AgentSessionId };
export type InterventionScope = InterventionTarget['scope'];
export type InterventionTargetId = InterventionTarget['targetId'];
export type InterventionKind =
  | 'product-decision'
  | 'missing-access'
  | 'destructive-action'
  | 'approval'
  | 'auth'
  | 'quota'
  | 'rate-limit'
  | 'agent-failure'
  | 'merge-conflict'
  | 'stuck-agent'
  | 'manual-intervention';
export type InterventionStatus = 'open' | 'acknowledged' | 'resolved' | 'dismissed';

/**
 * Structured failure classification carried by errors and outcomes so
 * interventions never depend on parsing human-readable summaries.
 */
export type FailureKind = Extract<
  InterventionKind,
  'auth' | 'quota' | 'rate-limit' | 'merge-conflict' | 'agent-failure'
>;

export type Intervention = InterventionTarget & {
  readonly id: InterventionId;
  readonly kind: InterventionKind;
  readonly status: InterventionStatus;
  readonly summary: string;
  readonly details?: string;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly resolvedAt?: string;
};

export interface Repository {
  readonly id: RepositoryId;
  readonly name: string;
  readonly reference: ScmReference;
  readonly defaultBranch: string;
}

export type PullRequestStatus = 'open' | 'merged' | 'closed';

export interface PullRequest {
  readonly id: PullRequestId;
  readonly repositoryId: RepositoryId;
  readonly number: number;
  readonly title: string;
  readonly status: PullRequestStatus;
  readonly sourceBranch: string;
  readonly targetBranch: string;
  /** Current source commit used for compare-and-merge protection when available. */
  readonly headSha?: string;
  readonly reference: ScmReference;
  readonly url?: string;
}

export type CheckStatus = 'queued' | 'running' | 'passed' | 'failed' | 'cancelled';

export interface Check {
  readonly id: CheckId;
  readonly pullRequestId: PullRequestId;
  readonly name: string;
  readonly status: CheckStatus;
  readonly detailsUrl?: string;
}

export interface Configuration {
  readonly id: ConfigurationId;
  readonly projectId?: ProjectId;
  readonly key: string;
  readonly value: unknown;
  readonly version: number;
  readonly updatedAt: string;
}

export class DomainValidationError extends Error {
  public constructor(message: string) {
    super(message);
    this.name = 'DomainValidationError';
  }
}

export class InvalidStateTransitionError extends DomainValidationError {
  public constructor(entity: string, from: string, to: string) {
    super(`Illegal ${entity} state transition: ${from} -> ${to}`);
    this.name = 'InvalidStateTransitionError';
  }
}

export function createStableId<Name extends string>(value: string): StableId<Name> {
  if (value.trim().length === 0) {
    throw new DomainValidationError('Stable identifiers must not be empty.');
  }

  return value as StableId<Name>;
}

export function createProjectId(value: string): ProjectId {
  return createStableId<'project'>(value);
}

export function createTaskId(value: string): TaskId {
  return createStableId<'task'>(value);
}

export function createTaskDependencyId(value: string): TaskDependencyId {
  return createStableId<'task-dependency'>(value);
}

export function createTaskGraphId(value: string): TaskGraphId {
  return createStableId<'task-graph'>(value);
}

export function createRunId(value: string): RunId {
  return createStableId<'run'>(value);
}

export function createWorkflowRunId(value: string): WorkflowRunId {
  return createStableId<'workflow-run'>(value);
}

export function createAgentSessionId(value: string): AgentSessionId {
  return createStableId<'agent-session'>(value);
}

export function createWorkspaceId(value: string): WorkspaceId {
  return createStableId<'workspace'>(value);
}

export function createInterventionId(value: string): InterventionId {
  return createStableId<'intervention'>(value);
}

export function createExecutionNodeId(value: string): ExecutionNodeId {
  return createStableId<'execution-node'>(value);
}

export function createRepositoryId(value: string): RepositoryId {
  return createStableId<'repository'>(value);
}

export function createPullRequestId(value: string): PullRequestId {
  return createStableId<'pull-request'>(value);
}

export function createCheckId(value: string): CheckId {
  return createStableId<'check'>(value);
}

export function createConfigurationId(value: string): ConfigurationId {
  return createStableId<'configuration'>(value);
}

export function createEventId(value: string): EventId {
  return createStableId<'event'>(value);
}

export function createChannelMessageId(value: string): ChannelMessageId {
  return createStableId<'channel-message'>(value);
}

export function validateProject(project: Project): void {
  assertNonEmpty(project.name, 'Project name');
  assertNonEmpty(project.createdAt, 'Project createdAt');
  assertNonEmpty(project.updatedAt, 'Project updatedAt');
}

export function validateTask(task: Task): void {
  assertNonEmpty(task.title, 'Task title');
  assertNonEmpty(task.createdAt, 'Task createdAt');
  assertNonEmpty(task.updatedAt, 'Task updatedAt');
}

export function validateTaskGraph(graph: TaskGraph): void {
  const taskIds = new Set(graph.taskIds);
  if (taskIds.size !== graph.taskIds.length) {
    throw new DomainValidationError('A task graph must not contain duplicate task IDs.');
  }

  const dependencyKeys = new Set<string>();
  const dependencyIds = new Set<TaskDependencyId>();
  const blockingEdges = new Map<TaskId, TaskId[]>();

  for (const dependency of graph.dependencies) {
    if (!taskIds.has(dependency.taskId) || !taskIds.has(dependency.dependsOnTaskId)) {
      throw new DomainValidationError('Task dependencies must reference tasks in their graph.');
    }
    if (dependency.taskId === dependency.dependsOnTaskId) {
      throw new DomainValidationError('A task cannot depend on itself.');
    }
    if (dependencyIds.has(dependency.id)) {
      throw new DomainValidationError('A task graph must not contain duplicate dependency IDs.');
    }
    dependencyIds.add(dependency.id);

    const key = `${dependency.taskId}:${dependency.dependsOnTaskId}:${dependency.kind}`;
    if (dependencyKeys.has(key)) {
      throw new DomainValidationError('A task graph must not contain duplicate dependencies.');
    }
    dependencyKeys.add(key);

    if (dependency.kind === 'blocks') {
      const edges = blockingEdges.get(dependency.taskId) ?? [];
      edges.push(dependency.dependsOnTaskId);
      blockingEdges.set(dependency.taskId, edges);
    }
  }

  const visiting = new Set<TaskId>();
  const visited = new Set<TaskId>();
  const visit = (taskId: TaskId): void => {
    if (visiting.has(taskId)) {
      throw new DomainValidationError('Blocking task dependencies must not contain cycles.');
    }
    if (visited.has(taskId)) {
      return;
    }

    visiting.add(taskId);
    for (const dependencyId of blockingEdges.get(taskId) ?? []) {
      visit(dependencyId);
    }
    visiting.delete(taskId);
    visited.add(taskId);
  };

  for (const taskId of graph.taskIds) {
    visit(taskId);
  }
}

/** Resolves a workspace path to the physical location used for uniqueness checks. */
export function canonicalizeWorkspacePath(workspacePath: string): string {
  const normalizedPath = resolve(workspacePath);
  let unresolvedPath = normalizedPath;
  const unresolvedSuffix: string[] = [];

  // Worktrees can be checked before their final directory exists. Resolve the
  // nearest existing ancestor so symlinked parent directories still identify
  // the same physical worktree as their real path.
  while (true) {
    try {
      return resolve(realpathSync.native(unresolvedPath), ...unresolvedSuffix.reverse());
    } catch {
      const parentPath = dirname(unresolvedPath);
      if (parentPath === unresolvedPath) {
        return normalizedPath;
      }

      unresolvedSuffix.push(basename(unresolvedPath));
      unresolvedPath = parentPath;
    }
  }
}

/**
 * Enforces the runtime invariant that each active task has one primary worktree
 * and that a primary worktree is never shared by two tasks.
 */
export function validatePrimaryWorktreeInvariant(
  activeTaskIds: readonly TaskId[],
  workspaces: readonly Workspace[],
): void {
  const activeTasks = new Set(activeTaskIds);
  if (activeTasks.size !== activeTaskIds.length) {
    throw new DomainValidationError('Active task IDs must be unique.');
  }

  const primaryByTask = new Map<TaskId, WorkspaceId>();
  const taskByCanonicalWorktreePath = new Map<string, TaskId>();

  for (const workspace of workspaces) {
    if (
      workspace.kind !== 'primary-worktree' ||
      (workspace.state !== 'provisioning' && workspace.state !== 'active')
    ) {
      continue;
    }

    const existingWorkspace = primaryByTask.get(workspace.taskId);
    if (existingWorkspace !== undefined) {
      throw new DomainValidationError(
        `Task ${workspace.taskId} has more than one primary worktree.`,
      );
    }

    const canonicalWorktreePath = canonicalizeWorkspacePath(workspace.path);
    const existingTask = taskByCanonicalWorktreePath.get(canonicalWorktreePath);
    if (existingTask !== undefined) {
      throw new DomainValidationError(
        `Primary worktree path ${workspace.path} is shared by multiple tasks.`,
      );
    }

    primaryByTask.set(workspace.taskId, workspace.id);
    taskByCanonicalWorktreePath.set(canonicalWorktreePath, workspace.taskId);
  }

  for (const taskId of activeTasks) {
    if (!primaryByTask.has(taskId)) {
      throw new DomainValidationError(`Active task ${taskId} has no primary worktree.`);
    }
  }
}

const agentSessionTransitions: Readonly<Record<AgentSessionState, readonly AgentSessionState[]>> = {
  starting: ['running', 'failed', 'stopped', 'interrupted'],
  running: ['waiting', 'blocked', 'completed', 'failed', 'stopped', 'interrupted'],
  waiting: ['running', 'blocked', 'completed', 'failed', 'stopped', 'interrupted'],
  blocked: ['running', 'failed', 'stopped', 'interrupted'],
  completed: [],
  failed: [],
  stopped: [],
  interrupted: ['starting'],
};

const runTransitions: Readonly<Record<RunState, readonly RunState[]>> = {
  queued: ['starting', 'failed', 'stopped', 'interrupted'],
  starting: ['running', 'failed', 'stopped', 'interrupted'],
  running: ['waiting', 'blocked', 'completed', 'failed', 'stopped', 'interrupted'],
  waiting: ['running', 'blocked', 'completed', 'failed', 'stopped', 'interrupted'],
  blocked: ['running', 'failed', 'stopped', 'interrupted'],
  completed: [],
  failed: [],
  stopped: [],
  interrupted: ['starting'],
};

export function canTransitionAgentSession(from: AgentSessionState, to: AgentSessionState): boolean {
  return agentSessionTransitions[from].includes(to);
}

export function canTransitionRun(from: RunState, to: RunState): boolean {
  return runTransitions[from].includes(to);
}

export function transitionAgentSession(
  session: AgentSession,
  nextState: AgentSessionState,
  updatedAt: string,
): AgentSession {
  if (!canTransitionAgentSession(session.state, nextState)) {
    throw new InvalidStateTransitionError('agent session', session.state, nextState);
  }

  if (isTerminalRuntimeState(nextState)) {
    return { ...session, state: nextState, updatedAt, completedAt: updatedAt };
  }

  return { ...session, state: nextState, updatedAt };
}

export function transitionRun(run: Run, nextState: RunState, updatedAt: string): Run {
  if (!canTransitionRun(run.state, nextState)) {
    throw new InvalidStateTransitionError('run', run.state, nextState);
  }

  if (isTerminalRuntimeState(nextState)) {
    return { ...run, state: nextState, updatedAt, completedAt: updatedAt };
  }

  return { ...run, state: nextState, updatedAt };
}

function assertNonEmpty(value: string, label: string): void {
  if (value.trim().length === 0) {
    throw new DomainValidationError(`${label} must not be empty.`);
  }
}

export function isTerminalRuntimeState(state: RuntimeState): state is TerminalRuntimeState {
  return state === 'completed' || state === 'failed' || state === 'stopped';
}
